name             'reboot_coordinator'
maintainer       'EverTrue'
maintainer_email 'devops@evertrue.com'
license          'Apache 2.0'
description      'Installs/Configures reboot_coordinator'
long_description 'Installs/Configures reboot_coordinator'
version          '2.0.1'

depends 'ohai', '>= 4.0'
depends 'build-essential'
