name             'reboot_coordinator'
maintainer       'EverTrue'
maintainer_email 'devops@evertrue.com'
license          'all_rights'
description      'Installs/Configures reboot_coordinator'
long_description 'Installs/Configures reboot_coordinator'
version          '0.1.0'
